### ISSUE TITLE
Update for Git Updater 

### ISSUE THREAD

**Issue by afragen** [palmiak/deploy-buddy#1]
It appears that you have set the default branch to `main`. In order for Git Updater to function correctly you must add the following header, `Primary Branch: main`. 

https://git-updater.com/knowledge-base/required-headers/

**Comment by palmiak** [comment]
Hi :)

Overall it's correct as it is because:
- main - this the main production branch - as you see it doesn't has the vendor, this one should be a base of each PR.
- master - this is automatically generated - it has the composer update running before

The only thing I should correct is the naming of master branch to something... better and create some documentation on contributing.
